# Generated by Django 2.2.3 on 2019-07-09 10:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': '选项表'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': '问题表'},
        ),
        migrations.AlterModelManagers(
            name='choice',
            managers=[
                ('myobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='desc',
            field=models.CharField(help_text='选项描述', max_length=20, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='vote',
            field=models.IntegerField(blank=True, default=0, help_text='选项票数', null=True, verbose_name='票数'),
        ),
    ]
