# Generated by Django 2.2.3 on 2019-07-17 01:50

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('recommend', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('focus', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='bootcamp_img')),
                ('inform', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '训练营课程表',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '实验课程类别表',
            },
        ),
        migrations.CreateModel(
            name='ExperimentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=10)),
                ('list', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '实验课程表',
            },
        ),
        migrations.CreateModel(
            name='PathCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pathcategory_img')),
            ],
            options={
                'verbose_name_plural': '路径课程分类表',
            },
        ),
        migrations.CreateModel(
            name='PathState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '路径课程阶段表',
            },
        ),
        migrations.CreateModel(
            name='ShiyanlouUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('vip', models.BooleanField(default=False)),
                ('advancevip', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '实验课程标签表',
            },
        ),
        migrations.CreateModel(
            name='PathCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='path_img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.PathCategory')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.PathState')),
            ],
            options={
                'verbose_name_plural': '路径课程表',
            },
        ),
        migrations.CreateModel(
            name='PathComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('pathcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.PathCourse')),
            ],
            options={
                'verbose_name_plural': '路径课程评论表',
            },
        ),
        migrations.CreateModel(
            name='ExperimentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('focus', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='experiment_img')),
                ('vip', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.Category')),
                ('experimentlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.ExperimentList')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.Tags')),
            ],
            options={
                'verbose_name_plural': '实验课程表',
            },
        ),
        migrations.CreateModel(
            name='ExperimentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('experimentcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.ExperimentCourse')),
            ],
            options={
                'verbose_name_plural': '实验课程评论表',
            },
        ),
        migrations.CreateModel(
            name='BootcampInform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('bootcampcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.BootcampCourse')),
            ],
            options={
                'verbose_name_plural': '训练营课程实验报告',
            },
        ),
        migrations.CreateModel(
            name='BootcampCourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=20)),
                ('bootcampcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.BootcampCourse')),
            ],
            options={
                'verbose_name_plural': '训练营课程表',
            },
        ),
        migrations.CreateModel(
            name='BootcampComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('bootcampcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.BootcampCourse')),
            ],
            options={
                'verbose_name_plural': '训练营课程评论',
            },
        ),
        migrations.CreateModel(
            name='BootcampAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
                ('bootcampcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.BootcampCourse')),
            ],
            options={
                'verbose_name_plural': '训练营课程实验回答',
            },
        ),
    ]
