# Generated by Django 2.2.3 on 2019-07-17 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiyanlou', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentlist',
            options={'verbose_name_plural': '实验课程列表表'},
        ),
        migrations.RemoveField(
            model_name='experimentcourse',
            name='experimentlist',
        ),
        migrations.AddField(
            model_name='experimentlist',
            name='experimentcourse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shiyanlou.ExperimentCourse'),
        ),
    ]
